# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Description of what the lane does"
  private_lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Register Your App"
  private_lane :register_app do
    produce
  end

  desc "Cert Your App"
  private_lane :get_dev_certs do
    cert(development: true)
    sigh(development: true)
  end

  desc "Sync All Devices"
  lane :sync_all_development do
    sync_devices
    match(type: "development")
  end

  desc "Sync devices info"
  private_lane :sync_devices do
    register_devices(
        devices_file: "fastlane/Devicefile"
    )
  end
  
  desc "Package"
  lane :package do
    cert(development: false)
    sigh(development: false)
    match(type: "adhoc")
    gym(
      scheme: "OrzReader",
      output_directory: "build_Adhoc",
      export_method: "ad-hoc"
    )
  end

end
