# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Sync devices info"
  private_lane :sync_devices do
    register_devices(
        devices_file: "fastlane/Devicefile"
    )
  end
  
  desc "certs"
  lane :certs do
    match(type: "development")
    match(type: "adhoc")
    match(type: "appstore")
  end

  desc "adhoc package"
  lane :adhoc do
    cocoapods(
      try_repo_update_on_error: true
    )
    sigh(adhoc: true)
    gym(
      scheme: "OrzReader",
      export_method: "ad-hoc",
      output_directory: "./build_Adhoc"
    )
  end

end
